
spring.data.mongodb.uri=mongodb://localhost:27017/learnup
spring.main.allow-bean-definition-overriding=true
spring.security.user.name=admin
spring.security.user.password=admin
jwt.secret=mySuperSecretKeyForLearnUpProject2026!!!
